### ISSUE TITLE
German localizations issue

### ISSUE THREAD

**Issue by mbg033** [monero-project/monero-core#11]
@JamesCullum, could you please re-do it with Qt Linguist? Right now it can't be opened with Qt and it breaks the build
https://gyazo.com/4fe97d4c4fd4d924061bb2122cca5d52

**Comment by JamesCullum** [comment]
The installation of Qt Linguist crashed continously, thats why i had to do it via Notepad++ and asked for verification on the PR. Re-doing it would also be quite tedious so id rather fix the existing one.

Ironically, i wanted to make sure to not break anything and only used those html entities instead of non-english letters. The error comes from the html entitity that i used to replace german special characters, n this specific case, &uuml; equals the ü. I think i read somewhere in the Qt docs that this is how language specific characters are supposed to be used.

Can you try replacing the following sequences and check if it works then?

```
&uuml; => ü
&Uuml; => Ü
&auml; => ä
&Auml; => Ä
&ouml; => ö
&Ouml; => Ö`
```

**Comment by devinjdawson** [comment]
@JamesCullum which files?

**Comment by JamesCullum** [comment]
What are you talking about?

**Comment by devinjdawson** [comment]
I get an error "&uuml;" is undefined, when trying to compile the localization files. on Ubuntu 16.04. I can't find `uuml` in the source.

**Comment by JamesCullum** [comment]
Then your tool compiles this code already to the special characters. Open the original files with a text editor and replace it.

**Comment by devinjdawson** [comment]
which files

**Comment by JamesCullum** [comment]
The file of the german translation, which is the only one i edited and the one that gives you the error during compilation?!

**Comment by devinjdawson** [comment]
The files that are mentioned in the error are never created. When I look at the source, the term `uuml` is not present. This is why I do not know which files you are asking me to edit.

This is the exact error I get:

```
monero@monerocomputer:~/monero-core$ sudo make
/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease -compress -nounfinished -removeidentical translations/monero-core_de.ts -qm /home/monero/monero-core/release/bin/translations/monero-core_de.qm
lrelease error: Parse error at translations/monero-core_de.ts:9:41: Entity 'uuml' not declared.
Makefile:412: recipe for target 'release/bin/translations/monero-core_de.qm' failed
make: *** [release/bin/translations/monero-core_de.qm] Error 1
```

**Comment by JamesCullum** [comment]
Are you using the current code? According to [this PR](https://github.com/monero-project/monero-core/pull/14/commits/f2a126790a777c6dce5370921f5461f7627f8e5e) it should be fixed already.

**Comment by mbg033** [comment]
yep, fixed
