### ISSUE TITLE
Numerical value instead of (all)

### ISSUE THREAD

**Issue by relics219** [monero-project/monero-core#335]
A small suggestion: when sending the maximum amount of Monero in your wallet would it be possible to have the actual number minus tx fees instead of (all)?

**Comment by xmr-eric** [comment]
It's a good idea, but the problem is that the sweep_all command is a calculation of the total balance minus the fee. The wallet would need to create the transaction (total balance - fees = the amount sent) even before you hit the Send button.

Perhaps in the future transactions could be calculated on the fly or something, but for now I don't see this changing.

**Comment by moneromooo-monero** [comment]
Correct. It has to stay a placeholder for the reason above.

**Comment by xmr-eric** [comment]
This issue can probably be closed

**Comment by dEBRUYNE-1** [comment]
+resolved
