### ISSUE TITLE
build.sh fails on openSUSE - qmake not found

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#358]
```
./build.sh: line 68: qmake: command not found
make: *** No targets specified and no makefile found.  Stop.
cp: cannot create regular file 'release/bin': No such file or directory

```

'qmake' is 'qmake-qt5' on openSUSE.

**Comment by xmr-eric** [comment]
It looks as if you didn't add Qt bin dir to your path:

`export PATH=$PATH:$HOME/Qt/5.7/clang_64/bin`

where Qt is the folder you selected to install Qt.

Did that work?

**Comment by Jaqueeee** [comment]
if qmake-qt5 is in your path you can create an alias or a symlink from qmake->qmake-qt5.
You can add `alias qmake='qmake-qt5'`to your `.bashrc` in home folder

**Comment by voidzero** [comment]
I don't think that aliases are used by scripts. In the case of Gentoo, qmake for qt5 is at /usr/lib64/qt5/bin/qmake. That could either be added to the path by the user, but it'd be more convenient to have something like this on a separate line: `: ${QMAKE:-/usr/bin/qmake}`, and consequently use `$QMAKE` rather than `qmake`.

**Comment by medusadigital** [comment]
can this be closed ?

**Comment by voidzero** [comment]
@peronero can you try to do the following:

`QT_SELECT=5 ./build.sh`

See if that works. If so, we can ask @glv2 to add OpenSUSE next to Gentoo, in #637.

If you already have it working, or lost interest, please close this bug.
