### ISSUE TITLE
Suggestion for Beta GUI Warning

### ISSUE THREAD

**Issue by ForeignWaters** [monero-project/monero-core#423]
I think the average person doesn't understand what software in beta status means. From Wikipedia:

> Beta phase generally begins when the software is feature complete but **likely to contain a number of known or unknown bugs.** Software in the beta phase will generally have many more bugs in it than completed software, as well as speed/performance issues and **may still cause crashes or data loss.**

If someone expects it to be perfect and runs into problems, they will be turned away from using Monero and hinder its growth. They might even dissuade others from using Monero or cryptocurrencies all together.

Perhaps there should be a warning screen when they first run the GUI saying, "This is in beta for testing purposes, bugs may occur. Use the CLI for regular transactions." With an "I understand" button.

**Comment by medusadigital** [comment]
i stated my opinion allready in the reddit thread that a warning is (especially with increasing quality) unneeded.

To maybe add : technically speaking, the two wallets (CLI and GUI) use the exact same RPC Calls and if there is a serious bug, its mostly going to affect both wallets anyway. 

since in my opinion the current state is absolutely secure (impossible to lose money), i am against such a warning.

**Comment by moneromooo-monero** [comment]
Has anything actually been lost ? What problem(s) you refering to for wanting such a warning ?

**Comment by xmr-eric** [comment]
I think he's mostly asking for it as a best practice. However the title of the filename includes the word "beta", so perhaps we could have a warning in an enclosed readme, but I don't think we need an actual in-GUI warning screen.

**Comment by medusadigital** [comment]
with Beta 2 released, and probably a 3rd Beta on its way, i think this can be closed

**Comment by dEBRUYNE-1** [comment]
+resolved
